### ISSUE TITLE
Support determining size of images programmatically

### ISSUE THREAD

**Issue by tmcw** [mapbox/node-blend#59]

**Comment by springmeyer** [comment]
Node-blend could def offer a fast API for this. Under the hood we'd expose the mapnik::image_reader interface which has the ability to read just headers without allocating any data. However, as discussed on chat https://github.com/mapbox/tiletype/blob/master/index.js#L87-L146 already does this, so I think that should work fine?

**Comment by tmcw** [comment]
Yep, I used tiletype for my usecase and it worked great - no need to duplicate the functionality here.
