### ISSUE TITLE
mapnik-config: not found

### ISSUE THREAD

**Issue by strarsis** [mapbox/node-blend#66]
During installation of blend package from npm, build fails with:

```
[...]
/bin/sh: 1: mapnik-config: not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
[...]
```

Ideally, the mapnik(-config) dependency is just stripped from this module.

**Comment by springmeyer** [comment]
This module depends on node-mapnik. By default node-mapnik is installed via a binary and therefore no external dependencies are needed. If `mapnik-config` is being looked for that means the binary install of node-mapnik did not work for your platform. In that case please provide a detailed error reporting to https://github.com/mapnik/node-mapnik/issues with your platform and node version.
