### ISSUE TITLE
Failing to install package node-pre

### ISSUE THREAD

**Issue by zeilmannnoah** [mapbox/node-blend#73]
Trying to install this package for the first time and I am having problems, does anyone know whats up?
I'm on a window 10 machine and I have already installed windows build tools before. My node version is v8.9.1 and my NPM version is 6.4.1. Here's my error message below, I left out some of the stack trace but I can post more if needed

> node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@8.9.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
'mapnik-config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'mapnik-config --ldflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Noah\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Noah\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Noah\\Documents\\Mosaic\\node_modules\\mapnik\\lib\\binding\\node-v57-win32-x64\\mapnik.node" "--module_name=mapnik" "--module_path=C:\\Users\\Noah\\Documents\\Mosaic\\node_modules\\mapnik\\lib\\binding\\node-v57-win32-x64" "--python=C:\\Users\\Noah\\.windows-build-tools\\python27\\python.exe"
gyp ERR! cwd C:\Users\Noah\Documents\Mosaic\node_modules\mapnik
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by philmander** [comment]
The README is outdated and you need to install `@mapbox/blend`

**Comment by mapsam** [comment]
Yep @philmander is correct - please try installing `@mapbox/blend@2.0.0` and you'll get a more up-to-date version of mapnik which has pre-built binaries for node 8.x. I'll update the readme!

**Comment by mapsam** [comment]
Err, @ian29 will update the readme https://github.com/mapbox/node-blend/pull/72 😄

**Comment by ian29** [comment]
#72 is merged (thx @millzpaugh)!

@zeilmannnoah try using node-blend v2.0.1 with node v8.x.

**Comment by omerkaramanli** [comment]
I too am trying to install the package with npm install @mapbox/blend --save and im getting the response below. Tried visiting 
https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/win32-x64.tar.gz and it shows an xml with Access Denied message. 

> npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@16.15.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\Ömer\Desktop\harver\node_modules\mapnik\lib\binding\mapnik.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/win32-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/win32-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for mapnik@4.5.9 and node@16.15.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/win32-x64.tar.gz
